// data.js
const cars = [
  {
    id: 1,
    name: 'Camry',
    brand: 'Toyota',
    model: 'XLE',
    price: 28000,
    image: 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg',
    fuelType: 'Petrol',
    seatingCapacity: 5,
    engine: '2.5L 4-Cylinder',
    year: 2024,
    desc: 'The Toyota Camry XLE is a midsize sedan that combines elegance with reliability. Its sleek exterior lines are matched with a spacious and refined cabin, featuring premium materials and advanced technology like a touchscreen infotainment system, Apple CarPlay, and adaptive cruise control. The 2.5L 4-cylinder engine ensures smooth acceleration and great fuel economy, making it perfect for both long road trips and daily commutes. With Toyota’s legendary safety features and durability, the Camry remains a top choice for comfort-seeking families and professionals.'
  },
  {
    id: 2,
    name: 'Civic',
    brand: 'Honda',
    model: 'Touring',
    price: 27000,
    image: 'https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg',
    fuelType: 'Petrol',
    seatingCapacity: 5,
    engine: '1.5L Turbocharged',
    year: 2023,
    desc: 'The Toyota Camry XLE is a midsize sedan that combines elegance with reliability. Its sleek exterior lines are matched with a spacious and refined cabin, featuring premium materials and advanced technology like a touchscreen infotainment system, Apple CarPlay, and adaptive cruise control. The 2.5L 4-cylinder engine ensures smooth acceleration and great fuel economy, making it perfect for both long road trips and daily commutes. With Toyota’s legendary safety features and durability, the Camry remains a top choice for comfort-seeking families and professionals.'
  },
  {
    id: 3,
    name: 'Model 3',
    brand: 'Tesla',
    model: 'Long Range',
    price: 48000,
    image: 'https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg',
    fuelType: 'Electric',
    seatingCapacity: 5,
    engine: 'Dual Motor',
    year: 2024,
    desc: 'The Toyota Camry XLE is a midsize sedan that combines elegance with reliability. Its sleek exterior lines are matched with a spacious and refined cabin, featuring premium materials and advanced technology like a touchscreen infotainment system, Apple CarPlay, and adaptive cruise control. The 2.5L 4-cylinder engine ensures smooth acceleration and great fuel economy, making it perfect for both long road trips and daily commutes. With Toyota’s legendary safety features and durability, the Camry remains a top choice for comfort-seeking families and professionals.'
  },
  {
    id: 4,
    name: 'Mustang',
    brand: 'Ford',
    model: 'GT',
    price: 55000,
    image: 'https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg',
    fuelType: 'Petrol',
    seatingCapacity: 4,
    engine: '5.0L V8',
    year: 2023,
    desc: 'The Toyota Camry XLE is a midsize sedan that combines elegance with reliability. Its sleek exterior lines are matched with a spacious and refined cabin, featuring premium materials and advanced technology like a touchscreen infotainment system, Apple CarPlay, and adaptive cruise control. The 2.5L 4-cylinder engine ensures smooth acceleration and great fuel economy, making it perfect for both long road trips and daily commutes. With Toyota’s legendary safety features and durability, the Camry remains a top choice for comfort-seeking families and professionals.'
  },
  {
    id: 5,
    name: 'A4',
    brand: 'Audi',
    model: 'Premium Plus',
    price: 42000,
    image: 'https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg',
    fuelType: 'Petrol',
    seatingCapacity: 5,
    engine: '2.0L TFSI',
    year: 2024,
    desc: 'The Toyota Camry XLE is a midsize sedan that combines elegance with reliability. Its sleek exterior lines are matched with a spacious and refined cabin, featuring premium materials and advanced technology like a touchscreen infotainment system, Apple CarPlay, and adaptive cruise control. The 2.5L 4-cylinder engine ensures smooth acceleration and great fuel economy, making it perfect for both long road trips and daily commutes. With Toyota’s legendary safety features and durability, the Camry remains a top choice for comfort-seeking families and professionals.'
  },
  {
    id: 6,
    name: 'Seltos',
    brand: 'Kia',
    model: 'GTX Plus',
    price: 23000,
    image: 'https://images.pexels.com/photos/112460/pexels-photo-112460.jpeg',
    fuelType: 'Petrol',
    seatingCapacity: 5,
    engine: '1.4L Turbo GDI',
    year: 2023,
    desc: 'The Toyota Camry XLE is a midsize sedan that combines elegance with reliability. Its sleek exterior lines are matched with a spacious and refined cabin, featuring premium materials and advanced technology like a touchscreen infotainment system, Apple CarPlay, and adaptive cruise control. The 2.5L 4-cylinder engine ensures smooth acceleration and great fuel economy, making it perfect for both long road trips and daily commutes. With Toyota’s legendary safety features and durability, the Camry remains a top choice for comfort-seeking families and professionals.'
  },
  {
    id: 7,
    name: 'Creta',
    brand: 'Hyundai',
    model: 'SX (O)',
    price: 24000,
    image: 'https://images.pexels.com/photos/1149137/pexels-photo-1149137.jpeg',
    fuelType: 'Diesel',
    seatingCapacity: 5,
    engine: '1.5L CRDi',
    year: 2023,
    desc: 'The Toyota Camry XLE is a midsize sedan that combines elegance with reliability. Its sleek exterior lines are matched with a spacious and refined cabin, featuring premium materials and advanced technology like a touchscreen infotainment system, Apple CarPlay, and adaptive cruise control. The 2.5L 4-cylinder engine ensures smooth acceleration and great fuel economy, making it perfect for both long road trips and daily commutes. With Toyota’s legendary safety features and durability, the Camry remains a top choice for comfort-seeking families and professionals.'
  },
  {
    id: 8,
    name: 'Fortuner',
    brand: 'Toyota',
    model: 'Legender',
    price: 50000,
    image: 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg',
    fuelType: 'Diesel',
    seatingCapacity: 7,
    engine: '2.8L Diesel',
    year: 2024,
    desc: 'The Toyota Camry XLE is a midsize sedan that combines elegance with reliability. Its sleek exterior lines are matched with a spacious and refined cabin, featuring premium materials and advanced technology like a touchscreen infotainment system, Apple CarPlay, and adaptive cruise control. The 2.5L 4-cylinder engine ensures smooth acceleration and great fuel economy, making it perfect for both long road trips and daily commutes. With Toyota’s legendary safety features and durability, the Camry remains a top choice for comfort-seeking families and professionals.'
  },
  {
    id: 9,
    name: 'XUV700',
    brand: 'Mahindra',
    model: 'AX7',
    price: 32000,
    image: 'https://images.pexels.com/photos/112460/pexels-photo-112460.jpeg',
    fuelType: 'Petrol',
    seatingCapacity: 7,
    engine: '2.0L Turbo Petrol',
    year: 2024,
    desc: 'The Toyota Camry XLE is a midsize sedan that combines elegance with reliability. Its sleek exterior lines are matched with a spacious and refined cabin, featuring premium materials and advanced technology like a touchscreen infotainment system, Apple CarPlay, and adaptive cruise control. The 2.5L 4-cylinder engine ensures smooth acceleration and great fuel economy, making it perfect for both long road trips and daily commutes. With Toyota’s legendary safety features and durability, the Camry remains a top choice for comfort-seeking families and professionals.'
  },
  {
    id: 10,
    name: 'Thar',
    brand: 'Mahindra',
    model: 'LX 4x4',
    price: 25000,
    image: 'https://images.pexels.com/photos/1149137/pexels-photo-1149137.jpeg',
    fuelType: 'Diesel',
    seatingCapacity: 4,
    engine: '2.2L mHawk',
    year: 2023,
    desc: 'The Toyota Camry XLE is a midsize sedan that combines elegance with reliability. Its sleek exterior lines are matched with a spacious and refined cabin, featuring premium materials and advanced technology like a touchscreen infotainment system, Apple CarPlay, and adaptive cruise control. The 2.5L 4-cylinder engine ensures smooth acceleration and great fuel economy, making it perfect for both long road trips and daily commutes. With Toyota’s legendary safety features and durability, the Camry remains a top choice for comfort-seeking families and professionals.'
  },

  {
    id: 11,
    name: 'Altroz',
    brand: 'Tata',
    model: 'XZ Plus',
    price: 12000,
    image: 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg',
    fuelType: 'Petrol',
    seatingCapacity: 5,
    engine: '1.2L Revotron',
    year: 2023,
    desc: 'The Toyota Camry XLE is a midsize sedan that combines elegance with reliability. Its sleek exterior lines are matched with a spacious and refined cabin, featuring premium materials and advanced technology like a touchscreen infotainment system, Apple CarPlay, and adaptive cruise control. The 2.5L 4-cylinder engine ensures smooth acceleration and great fuel economy, making it perfect for both long road trips and daily commutes. With Toyota’s legendary safety features and durability, the Camry remains a top choice for comfort-seeking families and professionals.'
  },
  {
    id: 12,
    name: 'Venue',
    brand: 'Hyundai',
    model: 'SX Turbo',
    price: 18000,
    image: 'https://images.pexels.com/photos/112460/pexels-photo-112460.jpeg',
    fuelType: 'Petrol',
    seatingCapacity: 5,
    engine: '1.0L Turbo GDI',
    year: 2024,
    desc: 'The Toyota Camry XLE is a midsize sedan that combines elegance with reliability. Its sleek exterior lines are matched with a spacious and refined cabin, featuring premium materials and advanced technology like a touchscreen infotainment system, Apple CarPlay, and adaptive cruise control. The 2.5L 4-cylinder engine ensures smooth acceleration and great fuel economy, making it perfect for both long road trips and daily commutes. With Toyota’s legendary safety features and durability, the Camry remains a top choice for comfort-seeking families and professionals.'
  },
  {
    id: 13,
    name: 'Kushaq',
    brand: 'Skoda',
    model: 'Style',
    price: 22000,
    image: 'https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg',
    fuelType: 'Petrol',
    seatingCapacity: 5,
    engine: '1.5L TSI',
    year: 2023,
    desc: 'The Toyota Camry XLE is a midsize sedan that combines elegance with reliability. Its sleek exterior lines are matched with a spacious and refined cabin, featuring premium materials and advanced technology like a touchscreen infotainment system, Apple CarPlay, and adaptive cruise control. The 2.5L 4-cylinder engine ensures smooth acceleration and great fuel economy, making it perfect for both long road trips and daily commutes. With Toyota’s legendary safety features and durability, the Camry remains a top choice for comfort-seeking families and professionals.'
  },
  {
    id: 14,
    name: 'Compass',
    brand: 'Jeep',
    model: 'Limited',
    price: 36000,
    image: 'https://images.pexels.com/photos/1149137/pexels-photo-1149137.jpeg',
    fuelType: 'Diesel',
    seatingCapacity: 5,
    engine: '2.0L Multijet',
    year: 2024,
    desc: 'The Toyota Camry XLE is a midsize sedan that combines elegance with reliability. Its sleek exterior lines are matched with a spacious and refined cabin, featuring premium materials and advanced technology like a touchscreen infotainment system, Apple CarPlay, and adaptive cruise control. The 2.5L 4-cylinder engine ensures smooth acceleration and great fuel economy, making it perfect for both long road trips and daily commutes. With Toyota’s legendary safety features and durability, the Camry remains a top choice for comfort-seeking families and professionals.'
  },
  {
    id: 15,
    name: 'Sonet',
    brand: 'Kia',
    model: 'HTX',
    price: 16000,
    image: 'https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg',
    fuelType: 'Petrol',
    seatingCapacity: 5,
    engine: '1.2L Smartstream',
    year: 2023,
    desc: 'The Toyota Camry XLE is a midsize sedan that combines elegance with reliability. Its sleek exterior lines are matched with a spacious and refined cabin, featuring premium materials and advanced technology like a touchscreen infotainment system, Apple CarPlay, and adaptive cruise control. The 2.5L 4-cylinder engine ensures smooth acceleration and great fuel economy, making it perfect for both long road trips and daily commutes. With Toyota’s legendary safety features and durability, the Camry remains a top choice for comfort-seeking families and professionals.'
  },
  {
    id: 16,
    name: 'Baleno',
    brand: 'Maruti',
    model: 'Alpha',
    price: 13000,
    image: 'https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg',
    fuelType: 'Petrol',
    seatingCapacity: 5,
    engine: '1.2L DualJet',
    year: 2024,
    desc: 'The Toyota Camry XLE is a midsize sedan that combines elegance with reliability. Its sleek exterior lines are matched with a spacious and refined cabin, featuring premium materials and advanced technology like a touchscreen infotainment system, Apple CarPlay, and adaptive cruise control. The 2.5L 4-cylinder engine ensures smooth acceleration and great fuel economy, making it perfect for both long road trips and daily commutes. With Toyota’s legendary safety features and durability, the Camry remains a top choice for comfort-seeking families and professionals.'
  },
  {
    id: 17,
    name: 'Tiguan',
    brand: 'Volkswagen',
    model: 'Elegance',
    price: 40000,
    image: 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg',
    fuelType: 'Petrol',
    seatingCapacity: 5,
    engine: '2.0L TSI',
    year: 2024,
    desc: 'The Toyota Camry XLE is a midsize sedan that combines elegance with reliability. Its sleek exterior lines are matched with a spacious and refined cabin, featuring premium materials and advanced technology like a touchscreen infotainment system, Apple CarPlay, and adaptive cruise control. The 2.5L 4-cylinder engine ensures smooth acceleration and great fuel economy, making it perfect for both long road trips and daily commutes. With Toyota’s legendary safety features and durability, the Camry remains a top choice for comfort-seeking families and professionals.'
  },
  {
    id: 18,
    name: 'Q3',
    brand: 'Audi',
    model: 'Technology',
    price: 51000,
    image: 'https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg',
    fuelType: 'Petrol',
    seatingCapacity: 5,
    engine: '2.0L TFSI',
    year: 2023,
    desc: 'The Toyota Camry XLE is a midsize sedan that combines elegance with reliability. Its sleek exterior lines are matched with a spacious and refined cabin, featuring premium materials and advanced technology like a touchscreen infotainment system, Apple CarPlay, and adaptive cruise control. The 2.5L 4-cylinder engine ensures smooth acceleration and great fuel economy, making it perfect for both long road trips and daily commutes. With Toyota’s legendary safety features and durability, the Camry remains a top choice for comfort-seeking families and professionals.'
  },
  {
    id: 19,
    name: 'Scorpio N',
    brand: 'Mahindra',
    model: 'Z8L',
    price: 33000,
    image: 'https://images.pexels.com/photos/112460/pexels-photo-112460.jpeg',
    fuelType: 'Diesel',
    seatingCapacity: 7,
    engine: '2.2L mHawk',
    year: 2023,
    desc: 'The Toyota Camry XLE is a midsize sedan that combines elegance with reliability. Its sleek exterior lines are matched with a spacious and refined cabin, featuring premium materials and advanced technology like a touchscreen infotainment system, Apple CarPlay, and adaptive cruise control. The 2.5L 4-cylinder engine ensures smooth acceleration and great fuel economy, making it perfect for both long road trips and daily commutes. With Toyota’s legendary safety features and durability, the Camry remains a top choice for comfort-seeking families and professionals.'
  },
  {
    id: 20,
    name: 'Verna',
    brand: 'Hyundai',
    model: 'SX (O) Turbo',
    price: 22000,
    image: 'https://images.pexels.com/photos/1149137/pexels-photo-1149137.jpeg',
    fuelType: 'Petrol',
    seatingCapacity: 5,
    engine: '1.5L Turbo GDi',
    year: 2024,
    desc: 'The Toyota Camry XLE is a midsize sedan that combines elegance with reliability. Its sleek exterior lines are matched with a spacious and refined cabin, featuring premium materials and advanced technology like a touchscreen infotainment system, Apple CarPlay, and adaptive cruise control. The 2.5L 4-cylinder engine ensures smooth acceleration and great fuel economy, making it perfect for both long road trips and daily commutes. With Toyota’s legendary safety features and durability, the Camry remains a top choice for comfort-seeking families and professionals.'
  }
  ];
  
module.exports = cars;
  